-- AlterTable
ALTER TABLE "User" ALTER COLUMN "current_streak" DROP NOT NULL,
ALTER COLUMN "current_streak" SET DEFAULT 0,
ALTER COLUMN "level" DROP NOT NULL,
ALTER COLUMN "level" SET DEFAULT 1,
ALTER COLUMN "longest_streak" DROP NOT NULL,
ALTER COLUMN "longest_streak" SET DEFAULT 0,
ALTER COLUMN "xp" DROP NOT NULL,
ALTER COLUMN "xp" SET DEFAULT 0;
